##########################################
#
# sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Production file to remove volume mounts from docker-compose
#
##########################################

version: '2.4'

services:
  sparkswapd:
    image: sparkswap_sparkswapd:latest
    depends_on:
      - lnd_btc
      - lnd_ltc
    volumes:
      - './broker-daemon:/home/app/broker-daemon/'
      # TODO: This can be removed once utils are moved to a shared repo or into
      # the broker-daemon itself. broker-daemon relies on these utils for ./broker-daemon/bin/sparkswapd
      - './broker-cli/utils:/home/app/broker-cli/utils/'
      - './proto:/home/app/proto/'
      - './scripts:/home/app/scripts/'
    environment:
      # WARNING: only disable Relayer SSL/AUTH during development
      - DISABLE_RELAYER_AUTH=false

volumes:
  shared:
  sparkswapd:
