##########################################
# Sparkswap Broker Daemon Regtest development sample file
# https://sparkswap.com
#
# Usage:
# 1. copy file to `docker-compose.override.yml`
# 2. restart all containers with `docker-compose up -d`
##########################################

version: '2.4'

services:
  bitcoind:
    environment:
      - CONNECT_HOST=host.docker.internal
      - CONNECT_PORT=18666

  litecoind:
    environment:
      - CONNECT_HOST=host.docker.internal
      - CONNECT_PORT=19666
