/**
 * Default KCLI configuration
 *
 * WARNING: DO NOT EDIT THIS FILE
 *
 * To edit your configuration, edit the file at ~/.kcli.js
 * or copy sample-.kcli.js to ~/.kcli.js
 *
 * If you edit this file, the KCLI may behave in unexpected ways
 */

module.exports = {
  /**
   * Address of the host for the Broker Daemon GRPC Server
   * @type {String}
   * @default 'localhost:27492'
   */
  rpcAddress: 'localhost:27492'
}
