/**
 * Default SparkSwap CLI `sparkswap(1)` configuration
 *
 * WARNING: DO NOT EDIT THIS FILE
 *
 * To edit your configuration, edit the file at ~/.sparkswap.js
 * or copy sample-.sparkswap.js to ~/.sparkswap.js
 *
 * If you edit this file, the SparkSwap CLI may behave in unexpected ways
 */

module.exports = {
  /**
   * Address of the host for the Broker Daemon gRPC Server
   * @type {String}
   * @default 'localhost:27492'
   */
  rpcAddress: 'localhost:27492'
}
