version: '3'

services:
  kcli:
    image: kcli
    build:
      context: ./
      dockerfile: kinesis/Dockerfile
    volumes:
      - '../:/home/app'
    environment:
      - BROKER_DAEMON_HOST=0.0.0.0:27492
    networks:
      - broker
    working_dir: '/home/app'
    entrypoint: './bin/kcli'

  kbd:
    image: kbd
    build:
      context: ./
      dockerfile: kinesis/Dockerfile
    volumes:
      - '../:/home/app'
    environment:
      - NODE_PATH=.
      - RPC_ADDRESS=0.0.0.0:27492
      - DATA_DIR=/data
      - LND_RPC_HOST=0.0.0.0:10009
      - LND_TLS_CERT=/secure/tls.cert
      - LND_MACAROON=/secure/admin.macaroon
    networks:
      - broker
    working_dir: '/home/app'
    entrypoint: bash -c './bin/kbd'

volumes:
  data:

networks:
  broker:
